### PR TITLE
v1.0.0b

### LINKED ISSUE #48: Support for NUMBER Command Option Type (10)
Slash commands now support a `NUMBER` option type (10).  This type lets you accept floating-point numbers as input.

- [Documentation](https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type)

### LINKED ISSUE #50: DiscordResponse does not validate or throw error upon insufficient response
Attempting to send a `DiscordResponse` that does not contain `content` (or `embeds`?) but does contain an `action_row` is not a valid response. However, dispike will not throw an error of any kind when this interaction fails, the only indication that it was not successful is the Discord UI.

Example:
```py
@interactions.on("example")
async def ExampleCommand(ctx: IncomingDiscordInteraction) -> DiscordResponse:
    """Example command demonstrating DiscordResponse quietly failing."""

    return DiscordResponse(
        action_row=ActionRow(
            components=LinkButton(
                label="Example", url="https://github.com/ms7m/dispike"
            )
        )
    )
```

### LINKED ISSUE #51: Responding to Interactions does not require a Bot Token
According to the [Discord Slash Commands Documentation](https://discord.com/developers/docs/interactions/slash-commands#slash-commands-interactions-and-bot-users)...

> Slash Commands and Interactions bring something entirely new to the table: the ability to interact with an application without needing a bot user in the guild. As you read through this documentation, you'll see that bot tokens are only referenced as a helpful alternative to doing a client credentials auth flow. Slash Commands do not depend on a bot user in the guild; **responding to interactions does not require a bot token**.
> 
> In many cases, you may still need a bot user. If you need to receive gateway events, or need to interact with other parts of our API (like fetching a guild, or a channel, or updating permissions on a user), those actions are all still tied to having a bot token. However, if you don't need any of those things, **you never have to add a bot user to your application** at all.

It would seem that the `bot_token` argument for initializing a Dispike object should not be required. Dropping this requirement would mean one less step to beginning a project using Dispike and would keep things as efficient as possible.

Of course, it is possible that I'm underestimating the scope in which Dispike interacts with the API. In that case, this Issue is invalid.

### LINKED ISSUE #53: Support default_permission for DiscordCommand
- Relevant Documentation: [Slash Commands - Permissions](https://discord.com/developers/docs/interactions/slash-commands#permissions)

> You can also set a `default_permission` on your commands if you want them to be disabled by default when your app is added to a new guild. Setting `default_permission` to `false` will disallow anyone in a guild from using the command--even Administrators and guild owners--unless a specific overwrite is configured. It will also disable the command from being usable in DMs.

It would appear that this boolean value should be set on the `DiscordCommand` model after `options`.

### LINKED ISSUE #55: Support for Resolved Application Incoming Interaction Data
- https://discord.com/developers/docs/interactions/slash-commands#interaction-object-application-command-interaction-data-structure

### LINKED ISSUE #56: Possible Error in Event Callback Name Generation for Subcommands
My understanding is that Dispike generates callback names for commands, this process is not handled by Discord. Assuming this is in fact the case, this Issue describes what I feel to be unintuitive results from this process. When nesting a single level subcommand without the use of subcommand groups, the first argument name is included in the callback name.

The following example produces a callback name of `lorem.ipsum.dolor`.

However, the command usage is `/lorem ipsum dolor:VALUE sit:VALUE amet:VALUE`. Shouldn't the callback name be `lorem.ipsum`?

```py
DiscordCommand(
    name="lorem",
    description="...",
    options=[
        CommandOption(
            name="ipsum",
            description="...",
            type=CommandTypes.SUB_COMMAND,
            options=[
                CommandOption(
                    name="dolor",
                    description="..."
                    type=CommandTypes.STRING,
                    required=True,
                    choices=[...]
                ),
                CommandOption(
                    name="sit",
                    description="..."
                    type=CommandTypes.STRING,
                    required=True,
                    choices=[...]
                )
                CommandOption(
                    name="amet",
                    description="..."
                    type=CommandTypes.STRING,
                    required=True,
                    choices=[...]
                )
            ]
        )    
    ]
)
```

### PR DESCRIPTION
**Pull request by ms7m**
# New Features

- Support for "Application Command Interaction Data Resolved Structure". 

- Added ``.lookup_resolved_member``, ``.lookup_resolved_user``, ``.lookup_resolved_channel``, ``.lookup_resolved_role`` methods to ``IncomingDiscordInteraction``. (closes #55)

- Added ``Role``, ``PartialChannel``, ``PartialMember`` models.

- Added ``PerCommandRegistrationSettings`` object. This object is required to register commands located inside a ``EventCollection``.

- Added ``on`` function to ``dispike.interactions``. If you do not  wish to use an ``EventCollection``, you can use this function and later register it with Dispike by passing the function to ``.register_event_command``. 

- Added ``EventCollection`` to allow for similarly grouped commands to be developed in a single class. Feedback is helpful! #46
```python
class StockTicker(interactions.EventCollection):
    
    @staticmethod
    def command_schemas() -> typing.List[
        typing.Union[interactions.PerCommandRegistrationSettings, DiscordCommand]
    ]:
        """Return a list of commands to be registered
        """
        return [
            interactions.PerCommandRegistrationSettings(
                schema=DiscordCommand(
                    name="...",
                    description="....",
                    options=[],
                ),
                guild_id=11111111,
            )
        ]

    @interactions.on("....")
    async def sample_interactions(*args, **kwargs) -> DiscordResponse:
        return DiscordResponse(content="testing")
    
    @interactions.on("....")
    async def sample_interactions(*args, **kwargs) -> DiscordResponse:
        return DiscordResponse(content="testing")


# register collection 

bot = Dispike(...)
bot.register_event_collection(collection=StockTicker(), register_command_with_discord=True)

```
- Support for NUMBER Command Type (closes #48) 
- ``PermissionsGenerator`` is a helper class to assist you in creating proper permissions for a command. Punch in some arguments and it will spit out a ``NewApplicationPermission``. You can import it from ``dispike.helpers``
- Added a class for Deferred Empherical Responses. It is located in ``dispike.resposnes``. Functionality is identical to ``DeferredResponse``. 

# Breaking Changes

- ## 🚨 **Modules, classes and other items have been reorganized!**. Please read the changes on #52!

- ``bot.interactions.on`` has been deprecated. Please use ``bot.on`` instead or ``dispike.interactions.on``.
- ``EventHandler`` class has been removed, most of the functions have been implemented inside ``Dispike``
- The following commands now will raise an ``DiscordAPIError`` if the Discord API returns an unexpected status code. 
  - ``set_command_permission``
  - ``async_set_command_permission``
  - ``async_get_command_permission_in_guild``
  - ``async_get_all_command_permissions_in_guild``
  - ``get_all_command_permissions_in_guild``
  - ``get_command_permission_in_guild``
- Bot Tokens are no longer required to initialize a ``Dispike`` object.. Accessing methods, attributes or functions that require a bot token (such as registering commands) will now raise a new exception: ``dispike.errors.dispike.BotTokenNotProvided``. Certain features are still available without a bot token. Such as sending deferred messages or just responding to interactions. (closes #51) 
- DiscordResponse will now raise an exception ``dispike.errors.responses.InvalidDiscordResponse`` for certain combinations of values. (closes #50)
- Added ``default_permission`` to ``DiscordCommand``.. Learn more [here](https://discord.com/developers/docs/interactions/slash-commands#permissions). This value is set to ``True`` by default. (closes #53)

- Accessing methods such as ``.lookup_resolved_channel`` in ``IncomingDiscordInteraction`` with no resolved structures will now raise ``dispike.errors.response.NoResolvedInteractions``.

- ``CommandTypes`` has been changed to ``OptionTypes``. A new class of actual command types has been added. (thanks @mrshmllow)
- ``IncomingDiscordOptionList`` changed to ``IncomingDiscordSlashData`` to better match what it actually is. (thanks @mrshmllow)
- ``IncomingDiscordInteraction`` changed to ``IncomingDiscordSlashInteraction`` (thanks @mrshmllow)
- ``DiscordCommand`` now takes a type which defaults to ``CommandTypes.SLASH`` (AKA Type 1) (thanks @mrshmllow)
- ``DiscordCommand`` now validates that slash commands contain a description. (thanks @mrshmllow)
- ``DiscordCommand`` now validates that context commands (Currently only ``MESSAGE``, ``USER``) do not have a description or options. (thanks @mrshmllow)

- New events:  (thanks @mrshmllow)
    - ``MESSAGE_COMMAND``  
    - ``USER_COMMAND``

- New WIP classes ``Message`` and ``MessageAttachment``. Discord says they will add attachments as a option type in the future. (thanks @mrshmllow)
- New ``IncomingInteraction`` ctx classes ``IncomingDiscordUserCommandInteraction`` and ``IncomingDiscordMessageCommandInteraction`` (thanks @mrshmllow)

# Misc Fixes, and changes
- 🎉 **Dispike is now leaving alpha stage!** Thank you to all the contributors who helped out! While things are more stable, this library can still go through sudden breaking changes! Developers are encouraged to keep tabs on this repository and open issues for unexpected behaviors.
- ``UserWarnings`` and ``DeprecationWarnings`` will now appear on certain deprecated functions.
- Passing ``middleware_testing_skip_verification_key_request`` to Dispike will now disable the request verifier in ``DiscordVerificationMiddleware``. (If you are using ``DiscordVerificationMiddleware`` in another starlette-based application, you can pass ``testing_skip_verification_of_key`` to the middleware to skip checks).
- Command Choices will now accept integers and floats.
- You can now clear callbacks by using the method ``clear_all_event_callbacks`` on Dispike.
- All functions from ``EventHandler`` have been moved to the main dispike object.
- Logging to stdout will no longer be default in a future release of Dispike(You will need to pass a parameter ``enable_logging``) to enable logging. Developers are encouraged to still [configure logging through loguru's settings](https://loguru.readthedocs.io/en/stable/)
- Dispike will now log any outgoing http requests.
- Tweaks to event name callback determination. (closes #56)
- ``.get_commands``, ``.edit_commands`` and ``.delete_commands`` now can accept an ``IncomingApplicationCommand`` for argument ``command_id``.

### CODE REVIEW

**Comment by EthanC** [comment]
Super happy to see this coming together so quickly. If I could make a final suggestion or two before it's merged,

1. Support for the `NUMBER` Command Option Type (#48) would fit nicely with this release.
2. 1.0.0 is a great time for a Dispike Discord Server for announcements, support, etc. (briefly discussed in #32) to be opened!

**Comment by mrshmllow** [comment]
Docs need to be pretty much rewritten at this point

**Comment by EthanC** [comment]
The return type in the `get_commands` docstring should be updated to reflect the class name change.

```py
Returns a list of ``DiscordCommands`` either globally or for a specific guild.
```
to
```
Returns a list of ``IncomingApplicationCommand`` either globally or for a specific guild.
```

https://github.com/ms7m/dispike/blob/dev/dispike/main.py#L198

**Comment by EthanC** [comment]
@ms7m I don't believe that this is currently worthy of its own Issue, especially considering the statement that [reverse proxies are outside of the documentation scope](https://dispike.ms7m.me/tutorial/Running%20the%20bot/), so I think the discussion is best held here for the time being (or a Discord Server?) It may end with some changes to the Dispike v1.0.X codebase, but I'm happy to move the discussion if you'd prefer.

I noticed the [Example Server Configs](https://github.com/ms7m/dispike-example-server-configurations) repo (currently empty), and I was curious if you have successfully deployed a Dispike bot to production **with HTTPS**? While I'm admittedly new to this area, I can't seem to properly get my instance working and I'm wondering if this may be out of my control. In my research, I noticed that [uvicorn requires a certificate and extra arguments for HTTPS](https://www.uvicorn.org/deployment/#running-with-https).

Is it possible that Dispike currently cannot be hosted in a proper production environment as these arguments are not accessible?

**Comment by ms7m** [comment]
@EthanC, [i'm writing up the docs on methods to deploy with ](https://github.com/ms7m/dispike/tree/dev/docs/DeployingToProduction)
- a reverse proxy
- serverless platform (gcp, aws)
- straight up binding to custom ports/ips (useful for heroku)

I believe I added a sample configuration for nginx inside the docs, but I should probably move to that repo you mentioned. 

As for Uvicorn, you can follow the instructions in their documentation, simply substituting ``APP`` with ``<file_containing_dispike_instance>.referenced_application``.

This is a def an issue to be raised on their own, this library is designed for advanced users but it shouldn't scare newer users away.

**Comment by mrshmllow** [comment]
> 
> @EthanC, [i'm writing up the docs on methods to deploy with ](https://github.com/ms7m/dispike/tree/dev/docs/DeployingToProduction)
> - a reverse proxy
> - serverless platform (gcp, aws)
> - straight up binding to custom ports/ips (useful for heroku)
> 
> I believe I added a sample configuration for nginx inside the docs, but I should probably move to that repo you mentioned. 
> 
> As for Uvicorn, you can follow the instructions in their documentation, simply substituting ``APP`` with ``<file_containing_dispike_instance>.referenced_application``.
> 
> This is a def an issue to be raised on their own, this library is designed for advanced users but it shouldn't scare newer users away.

I have experience with GCP serverless using docker, I could probably write a guide on that.

**Pull request merged**
